
DOWNLOAD_DIR="/downloads"
ARIA2_CONF_DIR="/config"
ARIA2_CONF="${ARIA2_CONF_DIR}/aria2.conf"
SCRIPT_CONF="${ARIA2_CONF_DIR}/script.conf"
SCRIPT_DIR="${ARIA2_CONF_DIR}/script"

_GREEN_FONT_PREFIX="\033[32m"
_RED_FONT_PREFIX="\033[31m"
_YELLOW_FONT_PREFIX="\033[1;33m"
_FONT_COLOR_SUFFIX="\033[0m"
INFO="[${_GREEN_FONT_PREFIX}INFO${_FONT_COLOR_SUFFIX}]"
WARN="[${_YELLOW_FONT_PREFIX}WARN${_FONT_COLOR_SUFFIX}]"
ERROR="[${_RED_FONT_PREFIX}ERROR${_FONT_COLOR_SUFFIX}]"
DATE_TIME() { date -u +"%m/%d %T"; }
LOG_WITHOUT_TIMESTAMP=
_LOG_TIME() { [[ -z "${LOG_WITHOUT_TIMESTAMP}" ]] && echo "$(DATE_TIME)" || echo ""; }
LOGI() { echo -e "$(_LOG_TIME) ${INFO} $*"; }
LOGW() { echo -e "$(_LOG_TIME) ${WARN} $*"; }
LOGE() { echo -e "$(_LOG_TIME) ${ERROR} $*"; }
